name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-nginx .
          docker save my-nginx > my-nginx.tar
        env:
          DOCKER_BUILDKIT: 1

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ec2-3-236-188-246.compute-1.amazonaws.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Docker image to EC2
        run: scp -i ~/.ssh/id_rsa my-nginx.tar ubuntu@ec2-3-236-188-246.compute-1.amazonaws.com:/home/ubuntu/

      - name: Deploy Docker container on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@ec2-3-236-188-246.compute-1.amazonaws.com << 'EOF'
            docker load -i /home/ubuntu/my-nginx.tar
            docker run -d -p 80:80 --name my-nginx-container my-nginx 
